name: Kondukto Report to Slack

on:
  push:
  workflow_dispatch:

jobs:
  project_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.ids }}
    steps:
      - name: Install jq
        run: sudo apt-get install jq
      - run: |
          curl --location --request GET https://cedar.kondukto.io/api/v2/projects --header 'X-Cookie: ${{ secrets.KDT_TOKEN }}' >> projects.json
      - id: matrix
        run: |
          echo ::set-output name=ids::$(jq '[.projects|.[].id]' projects.json)
  report_to_slack:
    needs: [ project_matrix ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ids: ${{ fromJson(needs.project_matrix.outputs.matrix) }}
    steps:
      - name: Get Project Summary
        run: |
          curl --location --request GET https://cedar.kondukto.io/api/v2/projects/${{ matrix.ids }} \
          --header 'X-Cookie: ${{ secrets.KDT_TOKEN }}' >> slack-payload.json
      - name: Set Project Variables
        id: vars
        run: |
          echo ::set-output name=all::$(jq '{name, id, score, summary}' slack-payload.json)
      - name: Send Project Report to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: secops-testing
          slack-message: ${{ steps.vars.outputs.all }}

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
