name: Kondukto Report to Slack

on:
  push:
  workflow_dispatch:

jobs:
  KDT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Install jq
        run: sudo apt-get install jq
      - name: Get Project Summary
        run: |
          curl --location --request GET https://cedar.kondukto.io/api/v2/projects/6213ced12195e50f9f823000 \
          --header 'X-Cookie: ${{ secrets.KDT_TOKEN }}' | jq '{name, score, summary}' >> payload-slack-content.json
      - name: Post to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload-file-path: "./payload-slack-content.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HOOK }}
