name: Kondukto Report to Slack

on:
  push:
  workflow_dispatch:

jobs:
  KDT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Install KDT
        run: curl -sSL https://cli.kondukto.io | sudo sh
      - name: List Projects
        run: kdt list projects --host https://cedar.kondukto.io:8088 --token cHBBOVBtQUN2em1qM1drRmZrWHZlQ09jTmNuMnJMZVhONDJpeVZZN2VNajY5MFZRSEpXSXFjNmZ0Z2hW
