name: Panther Detection Linting

on: [pull_request, push]

# Panther Logtool Version for Download
env:
  VERSION: v1.17.0-RC

jobs:
  panther_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #pin to latest release: v2.3.4
      - name: Download Panther_Analysis_Tool
        run: curl -sSO "https://panther-community-us-east-1.s3.amazonaws.com/${{env.VERSION}}/tools/dev/pantherlog-linux-amd64" && mv pantherlog-linux-amd64 pantherlog && chmod +x pantherlog
      - name: Run Panther Schema Tests
        run: ./pantherlog -v && ./pantherlog test --path ./panther/panther_rules/
