name: Panther Detection Linting

on: [pull_request, push]

jobs:
  panther_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #pin to latest release: v2.3.4
      - name: Install Panther_Analysis_Tool
        run: pip3 install panther_analysis_tool
      - name: Download Pantherlog Tool
        env:
          VERSION: v1.17.0-RC
        run: curl -sSO "https://panther-community-us-east-1.s3.amazonaws.com/$VERSION/tools/dev/pantherlog-linux-amd64" && mv pantherlog-linux-amd64 pantherlog && chmod +x pantherlog
      - name: Schema Tests
        run: ./pantherlog parse --path ./schemas/
      - name: Detection Tests
        run: panther_analysis_tool test --path ./panther/panther_rules/
      - name: Test Loop
        env:
          FOLDERS: Hoodwink Dawnbreaker Marci
        run: |
          for f in $FOLDERS; 
          do echo f;
          done
          
