name: Panther Detection Linting

on:
  push:
    paths:
      - 'panther/**/'
  workflow_dispatch:

jobs:
  panther_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #pin to latest release: v2.3.4
      - name: Setup
        run: pip install pipenv && pipenv install --dev --target panther/Pipfile
      - name: Install Panther_Analysis_Tool
        run: pip3 install panther_analysis_tool
      - name: Panther Analysis Tool Test
        run: panther_analysis_tool test --path ./panther/panther_rules/
      - name: Install Pantherlog Tool
        env:
          VERSION: v1.17.0-RC
        run: curl -sSO "https://panther-community-us-east-1.s3.amazonaws.com/$VERSION/tools/dev/pantherlog-linux-amd64" && mv pantherlog-linux-amd64 pantherlog && chmod +x pantherlog
      - name: Schema Tests  # Relies on Naming Scheme (Directory Name).yml and (Directory Name)_tests.yml
        run: |
          for dir in ./panther/cedar_schemas/*;
            do if ! ./pantherlog test "$dir/$(basename $dir).yml" "$dir/$(basename $dir)_tests.yml"; then
              printf "No test files in $dir\nLooking for:\n\t$dir/$(basename $dir).yml\n\t$dir/$(basename $dir)_tests.yml"
              exit 2
            fi
          done
